version: '3'

services:
  nginx:
    image: nginx:1.23.4-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    tty: true
    restart: always
    depends_on:
      - web

  web:
    build: ./docker/web
    environment:
      PORT: '3000'
      HOST: '0.0.0.0'
    expose:
      - 3000
    volumes:
      - ./web:/app
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - api

  api:
    build: ./docker/api
    volumes:
      - ./api:/app
    expose:
      - 9000
    tty: true
    restart: always
